### ISSUE TITLE
HDMI license.

### ISSUE THREAD

**Issue by AnttiLukats** [machdyne/ddmi#1]
Hi

Sorry to say this but calling HDMI "DDMI" does not get around the HDMI licensing. As long as you are using HDMI connector and generating signals that can be received with HDMI monitor you need to be HDMI adopter and pay the fees.

**Comment by machdyne** [comment]
Hi. Thanks for your opinion.

The signalling is actually DVI, which existed before HDMI.

**Comment by AnttiLukats** [comment]
That you use DVI signalling does not matter. You use HDMI connector, HDMI cable and HDMI monitor so it is HDMI and needs HDMI license. This is PITA I know.

**Comment by machdyne** [comment]
I'm actually using a DVI cable and a DVI monitor. Again, thanks for your opinion.
